### ISSUE TITLE
可以发一下新版本的release吗

### ISSUE THREAD

**Issue by supermanxiacheng** [chroming/pdfdir#15]
我看#5里新版本好像支持负数页码？
试着按说明里的打包。提示如下错误
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>
去BootLoader里想再试试，看到This requires a recent version of Xcode (12.2 or later)。我用的是10.15.7的mac mini 2018款，没法升级了。
作者能更新一下吗？

**Comment by chroming** [comment]
过几天打包一个新版本😬

**Comment by chroming** [comment]
支持负数页的新版本重新打包了，有兴趣可以试用一下~: https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta2

**Comment by supermanxiacheng** [comment]
在我的mac上打不开，10.15.7。在dock里，跳了一下，就消失了。

**Comment by chroming** [comment]
> 在我的mac上打不开，10.15.7。在dock里，跳了一下，就消失了。

可以帮忙在terminal里打开看看报什么错么？

**Comment by supermanxiacheng** [comment]
[86474] Error loading Python lib '/var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib': dlopen: dlopen(/var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib, 10): Symbol not found: _preadv
  Referenced from: /var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib (which was built for Mac OS X 11.7)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib

**Comment by chroming** [comment]
> [86474] Error loading Python lib '/var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib': dlopen: dlopen(/var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib, 10): Symbol not found: _preadv
> 
>   Referenced from: /var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib (which was built for Mac OS X 11.7)
> 
>   Expected in: /usr/lib/libSystem.B.dylib
> 
>  in /var/folders/2m/70kw827x0q368ksr0js7l9k00000gn/T/_MEIhzDvqs/libpython3.10.dylib

怀疑是打包的macos版本太高导致的，用10.15重新打包了 https://github.com/chroming/pdfdir/releases/tag/v0.3.0-beta3 ，有空可以试下是否正常了

**Comment by Mamong** [comment]
@chroming 我用Python 3.7解决这个问题

**Comment by supermanxiacheng** [comment]
我可以打开了

**Comment by chroming** [comment]
github auto build macos最低版本已经升级到macos-11，去掉了10.15的打包环境： 

https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

v0.3.0-beta6 及之后的版本均使用macos-11+python3.7打包，如10.15有运行兼容性问题请重新打开此issue或提交新issue
