### ISSUE TITLE
老哥，你这个说明安装文档对编程小白来说是天书啊

### ISSUE THREAD

**Issue by JHSTONEGB** [chroming/pdfdir#2]
太简洁了，完全懵逼ing

**Comment by chroming** [comment]
具体是哪部分写的不够清楚, 我尝试完善下😂

**Comment by wangyexiang** [comment]
为啥报
![image](https://user-images.githubusercontent.com/23202109/49217534-c792c300-f408-11e8-864f-f1f1c498726c.png)，
![image](https://user-images.githubusercontent.com/23202109/49217554-d5e0df00-f408-11e8-8007-38bb4326d364.png)？

**Comment by chroming** [comment]
> 为啥报错
> ![image](https://user-images.githubusercontent.com/23202109/49217534-c792c300-f408-11e8-864f-f1f1c498726c.png)，
> ![image](https://user-images.githubusercontent.com/23202109/49217554-d5e0df00-f408-11e8-8007-38bb4326d364.png)？
> 
> 我用来生成《PyQt5快速开发与实战》这本书的标签，目录在京东上找的。

抱歉，我没新开分支更新代码，所以源码运行可能出现无法正常运行的情况😂等我近期有空了更新一个稳定版然后新开个稳定版分支

**Comment by chroming** [comment]
> 为啥报错
> ![image](https://user-images.githubusercontent.com/23202109/49217534-c792c300-f408-11e8-864f-f1f1c498726c.png)，
> ![image](https://user-images.githubusercontent.com/23202109/49217554-d5e0df00-f408-11e8-8007-38bb4326d364.png)？
> 
> 我用来生成《PyQt5快速开发与实战》这本书的标签，目录在京东上找的。



> 为啥报错
> ![image](https://user-images.githubusercontent.com/23202109/49217534-c792c300-f408-11e8-864f-f1f1c498726c.png)，
> ![image](https://user-images.githubusercontent.com/23202109/49217554-d5e0df00-f408-11e8-8007-38bb4326d364.png)？
> 
> 我用来生成《PyQt5快速开发与实战》这本书的标签，目录在京东上找的。

如果是源码运行的话可能是我源码更新的问题，如果是下载的运行包那我需要文件和标签文本来排查下原因

**Comment by GmtGongcheng** [comment]
老哥，你那个导航预览的功能实现了吗

**Comment by GmtGongcheng** [comment]
老哥，你那个导航预览的功能实现了吗

**Comment by chroming** [comment]
> 老哥，你那个导航预览的功能实现了吗

还没😰

**Comment by Tokubara** [comment]
开源的，人家没义务写得多详细，又不是靠这个教学生
