### ISSUE TITLE
macos安装软件后launch pad不显示图标

### ISSUE THREAD

**Issue by qizidog** [chroming/pdfdir#25]
好久没有升级软件了，之前用的还是v0.2版本，升级到最新版本后，软件图标没有了，并且launch pad不显示图标，让人很头痛

macos 12.6.6 Monterey

**Comment by chroming** [comment]
我周末重新打包试试😨

**Comment by qizidog** [comment]
launch pad可以正常显示图标了，虽然目前图标有点简陋 🤣  谢谢！
