### ISSUE TITLE
目录末尾的数字在有括号的情况下无法识别

### ISSUE THREAD

**Issue by dengfengliancui** [chroming/pdfdir#27]
必须将括号删去才能识别，更确切说是每行最后必须是数字才能准确识别。
![Snipaste_2023-10-20_09-31-37](https://github.com/chroming/pdfdir/assets/103981512/960471dd-da84-4aea-a3d8-1d8d30566f12)
![Snipaste_2023-10-20_09-38-49](https://github.com/chroming/pdfdir/assets/103981512/b1a783e5-4153-4bd8-b215-6650115ca54f)

**Comment by chroming** [comment]
refer: https://github.com/chroming/pdfdir/commit/e59bdd07dec19f338d761a8722bd64a14d4d2892
