### ISSUE TITLE
以空格缩进表示标题层级，但是正则无效，即使在VSCode中正常匹配

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [chroming/pdfdir#28]
我倾向于从豆瓣图书、超星读秀等地方复制目录，然后在VS Code中整理。

批量选择，然后按TAB，直接缩进4个空格，是比较符合直觉的层级标记方式。

但是不管我怎么写正则，都没法在软件中匹配，即使在VS Code中可以正常匹配。

如：

```Shell
一级标题
    二级标题
        三级标题
```

在VS Code中，可以使用正则匹配：

```Shell
.*
\s{4}.*
\s{8}.*
```

但是在软件中无效。

我觉得这是可以改进的，即对于为PDF增加目录这件事，不是在软件中用正则匹配层级，而是用户按照对应规则整理好层级，软件自动提取页码并偏移页码。

因为每本书的目录都不同，如果用正则去匹配，那么每本书都要写一次正则，像“第x章”、“第x节”这种，不可能符合所有书籍。

如果用户直接用空格缩进，软件识别0空格为一级，4空格为二级，8空格为三级，对于软件来说反而更简单。

**Comment by chroming** [comment]
很好的建议，之后会加上

**Comment by chroming** [comment]
#29
