### ISSUE TITLE
功能请求：载入PDF文件后尝试自动加载已有目录

### ISSUE THREAD

**Issue by qwinsi** [chroming/pdfdir#34]
比如说，myfile.pdf 本来是就是有 bookmark 的，那么在载入文件后，自动在左侧的「目录文本」区域加载好现有的 bookmark。

这样的话，在已有 bookmark 的基础上进行简单的修改就方便许多了。

以我浅显的了解，好像 PDF 的 bookmark 数据结构中的一个 item 对应的位置信息不只是简单的 pageNumber ，好像还可以精确到页内的一个点的坐标，要照顾到后者这种情况就比较费劲。但我想至少照顾到前者的 pageNumber 情况应该是比较好实现的，尤其是当 myfile.pdf 本来就曾经是由本软件 pdfdir 输出的的时候。

**Comment by chroming** [comment]
很好的建议! 我有空研究下怎么实现

**Comment by qwinsi** [comment]
发现 [从 v0.3.0-beta22 开始](https://github.com/chroming/pdfdir/compare/v0.3.0-beta21...v0.3.0-beta22) 已经实现了此功能了啊，向作者的付出表示感谢！
（这个 issue 应该可以 close 了）
