### ISSUE TITLE
[bug]有三级目录时识别正确但写入错误

### ISSUE THREAD

**Issue by proItheus** [chroming/pdfdir#8]
如图:
![Screenshot_20220303_103655](https://user-images.githubusercontent.com/50539150/156485502-656152dd-0707-422c-b925-ef6d7ec63af3.png)

写入后的pdf:

![Screenshot_20220303_103757](https://user-images.githubusercontent.com/50539150/156485611-e99c8a0e-1fc4-4649-99f3-73f975df98b7.png)

所有三级目录全都挤到第一个二级目录里去了……

**Comment by chroming** [comment]
标记一下周末改……

**Comment by chroming** [comment]
已修复～
